Clarify disconnect test
rapidsai/ucx-py pull request #645
Opened 2020-10-07 03:28 UTC by jakirkham

Fixes https://github.com/rapidsai/ucx-py/issues/643

Try to provide some more context about why this disconnect test may generate errors and what it is actually testing. Namely that the processes exit cleanly.

cc @madsbk @pentschev

2020-10-07 07:46 UTC, madsbk approved these changes
LGTM, thanks @jakirkham

2020-10-07 08:49 UTC, pentschev requested changes
Thanks @jakirkham , added a minor request to clarify that we're testing a clean server shutdown. Apart from that, it all looks good!

2020-10-07 08:49 UTC, pentschev commented on tests/test_disconnect.py
> +    Test clean client shutdown after unexpected peer close
```suggestion
    Test clean server shutdown after unexpected peer close
```

2020-10-07 08:50 UTC, pentschev requested changes
Thanks @jakirkham , added a minor request to clarify we're testing a clean _server_ shutdown. Apart from that, it all looks good!

2020-10-07 08:52 UTC, pentschev commented
Sorry for duplicating my request above, I thought the first one didn't go through.

2020-10-07 23:05 UTC, jakirkham commented
Thanks Peter. No worries. Have included the change :)

2020-10-08 08:01 UTC, pentschev approved these changes
LGTM, thanks @jakirkham !

2020-10-08 08:01 UTC, merged