Update install instructions for new UCX version
rapidsai/ucx-py pull request #666
Opened 2021-01-13 04:53 UTC by manopapad

Note that the "Edit on GitHub" links on https://ucx-py.readthedocs.io point to https://github.com/quasiben/ucx-py/tree/fix-rtd, so I don't know if these changes will get automatically applied.

2021-01-13 06:12 UTC, jakirkham commented
cc @quasiben (in case there’s something special we need to do with RTD per Manolis’ comment)

2021-01-13 09:20 UTC, pentschev approved these changes
LGTM, thanks @manopapad !

2021-01-14 15:06 UTC, quasiben commented
Thanks @manopapad -- I'm wondering if we should keep the 1.8 build instructions for a little bit while we sort out 1.10 UCX issues.  I'm happy to make the changes to this PR if you agree

2021-01-14 15:24 UTC, pentschev requested changes
Yes, that's a good idea, please refer to #668 . I'm blocking merging until we get things sorted out.

2021-01-26 21:04 UTC, quasiben commented
Pushed a commit to update instructions for both 1.9 and 1.8 ucx building

2021-02-05 23:45 UTC, jakirkham approved these changes

2021-02-06 01:43 UTC, jakirkham commented
Is this ok to merge Peter or are there other things we should be doing here? Seems like Ben has updated the instructions. Also it sounds like 1.9 doesn't have the problems we say in RCs of 1.10. Does that sound correct or are there things I've mixed up here?

2021-02-08 08:38 UTC, pentschev commented on docs/source/install.rst
> +    If you're running on a machine without CUDA then you _must NOT_ apply the patch.
```suggestion
    If you're running on a machine without CUDA then you _must NOT_ apply any of the patches above.
```

2021-02-08 08:40 UTC, pentschev commented
I did a minor phrasing modification, given we have instructions for both 1.8 and 1.9 above. Other than that, LGTM. Thanks @manopapad and @quasiben for the changes and @jakirkham for staying on top of this.

2021-02-08 08:40 UTC, pentschev approved these changes

2021-02-08 10:12 UTC, merged

2021-02-08 17:02 UTC, jakirkham commented
Thanks Peter! 😄