Reenable endpoint error handling
rapidsai/ucx-py pull request #693
Opened 2021-03-16 23:13 UTC by pentschev

2021-03-19 12:16 UTC, quasiben commented
This PR has all tests passing.  Are you still working on it ?

2021-03-23 23:21 UTC, pentschev commented
This is still not fully working, but I'm trying to get remaining issues rounded up. However, it would still be great to have your opinion here @madsbk , in particular with the change I had to make on creating endpoints.

In latest changes I moved `UCXWorker.ep_create*` to `UCXEndpoint.ep_create*` class methods, which is required so I can now pass `UCXEndpoint`'s `self` to the error handling callback function so it can cancel inflight messages, which otherwise makes it impossible to raise when an error occurs during `UCXEndpoint.tag_send_nb`/`UCXEndpoint.tag_recv_nb`.

Do you see any problems in doing the change above?

2021-04-07 14:48 UTC, madsbk commented
> In latest changes I moved `UCXWorker.ep_create*` to `UCXEndpoint.ep_create*` class methods, which is required so I can now pass `UCXEndpoint`'s `self` to the error handling callback function so it can cancel inflight messages, which otherwise makes it impossible to raise when an error occurs during `UCXEndpoint.tag_send_nb`/`UCXEndpoint.tag_recv_nb`.
> 
> Do you see any problems in doing the change above?

I cannot see why this is necessary? but I am fine with having the endpoint creation methods as class methods if we remove the `ep_` prefix :)

2021-04-07 16:17 UTC, pentschev commented
> I cannot see why this is necessary?

It is necessary because I now [pass the `UCXEndpoint`'s `self` attribute to the error callback](https://github.com/rapidsai/ucx-py/pull/693/files#diff-fcd6a3e983ecdd8df6934febc5776f1122186708a3dbb76bee29acd33f2b86caR662). This is later used in the callback to [assign the current error status of an endpoint](https://github.com/rapidsai/ucx-py/pull/693/files#diff-fcd6a3e983ecdd8df6934febc5776f1122186708a3dbb76bee29acd33f2b86caR336-R337) and [cancel inflight messages](https://github.com/rapidsai/ucx-py/pull/693/files#diff-fcd6a3e983ecdd8df6934febc5776f1122186708a3dbb76bee29acd33f2b86caR349).

> but I am fine with having the endpoint creation methods as class methods if we remove the `ep_` prefix :)

Good point, this is done now.

2021-05-18 16:00 UTC, pentschev commented
I believe this is finally good now. On local testing this now seems to work properly, including Dask with endpoint error handling with InfiniBand -- one of the main motivators for this change, avoiding nasty hangs when the other endpoint has closed. Note that endpoint error handling is only active by default in UCX 1.11 (current master) and above, because CUDA IPC error handling is only introduced in https://github.com/openucx/ucx/pull/6352 , and before that CUDA IPC would be quietly disabled if error handling was active.

@madsbk @quasiben would you be able to take a look?

2021-05-20 14:11 UTC, madsbk requested changes
LGTM @pentschev, nice work!
I only have some few suggestions

2021-05-20 14:11 UTC, madsbk commented on ucp/_libs/ucx_endpoint.pyx
>      # TODO: Support UCP_EP_CLOSE_MODE_FORCE
```suggestion
```

2021-05-20 14:11 UTC, madsbk commented on ucp/_libs/ucx_endpoint.pyx
> +
```suggestion
```

2021-05-20 19:08 UTC, pentschev commented on ucp/_libs/ucx_endpoint.pyx
>      # TODO: Support UCP_EP_CLOSE_MODE_FORCE
Done.

2021-05-20 19:08 UTC, pentschev commented on ucp/_libs/ucx_endpoint.pyx
> +        free(<void *>params)
I think you're mixing up the objects. Notice here `params` is only used within the constructor itself when passed to `ucp_ep_create` which is synchronous, and there's no `c_util_sockaddr_free` in the constructor, therefore freeing it just after `ucp_ep_create` should be fine.

2021-05-20 19:08 UTC, pentschev commented on ucp/_libs/ucx_endpoint.pyx
> +            c_util_sockaddr_free(&params.sockaddr)
Nice catch! Done.

2021-05-20 19:08 UTC, pentschev commented on ucp/_libs/ucx_endpoint.pyx
> +        return cls(worker, <uintptr_t>params, endpoint_error_handling)
Another nice catch! Done.

2021-05-20 19:09 UTC, pentschev commented on ucp/_libs/ucx_endpoint.pyx
> +
Done.

2021-05-20 19:09 UTC, pentschev commented
Thanks for the review @madsbk , I think I addressed all your comments. Would you mind taking another look?

2021-05-20 19:29 UTC, pentschev commented on ucp/_libs/ucx_endpoint.pyx
> +        free(<void *>params)
You were right all along. I missed the fact that `params` in the constructor _is_ the `params` object passed from the `classmethod` implementations. Fixed now.

2021-05-21 07:26 UTC, madsbk approved these changes
Looks good @pentschev, thanks for working on this!

2021-05-21 08:29 UTC, pentschev commented
Thanks @madsbk !

2021-05-21 08:31 UTC, merged