Fix "assignment makes pointer from integer without a cast" warnings
rapidsai/ucx-py pull request #713
Opened 2021-04-23 11:02 UTC by pentschev

Fixes a couple of build warnings:

```cpp
  ucp/_libs/ucx_api.c: In function ‘__pyx_pf_3ucp_5_libs_7ucx_api_18_ucx_mem_handle_finalizer’:
  ucp/_libs/ucx_api.c:16449:18: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
     __pyx_v_handle = __pyx_v_handle_as_int;
                    ^
  ucp/_libs/ucx_api.c: In function ‘__pyx_pf_3ucp_5_libs_7ucx_api_22_ucx_remote_mem_finalizer_post_flush’:
  ucp/_libs/ucx_api.c:20611:23: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
     __pyx_v_rkey_handle = ((uintptr_t)__pyx_v_rkey->_handle);
                         ^
```

2021-04-23 11:03 UTC, pentschev commented
@MattBBaker FYI

2021-04-26 08:31 UTC, madsbk requested changes
LGTM, just a minor simplification

2021-04-26 08:31 UTC, madsbk commented on ucp/_libs/ucx_rkey.pyx
> +    cdef ucp_rkey_h rkey_handle = <ucp_rkey_h><void *>rkey._handle
```suggestion
    ucp_rkey_destroy(rkey._handle)
```

2021-04-26 08:31 UTC, madsbk commented on ucp/_libs/ucx_rkey.pyx
> +    cdef ucp_rkey_h rkey_handle = <ucp_rkey_h><void *>rkey._handle
No need to cast at all

2021-04-26 08:33 UTC, pentschev commented on ucp/_libs/ucx_rkey.pyx
> +    cdef ucp_rkey_h rkey_handle = <ucp_rkey_h><void *>rkey._handle
Good catch, applied that. Thanks Mads!

2021-04-26 08:34 UTC, madsbk approved these changes

2021-04-26 08:34 UTC, madsbk commented on ucp/_libs/ucx_rkey.pyx
>      ucp_rkey_destroy(rkey_handle)
```suggestion
```

2021-04-26 08:35 UTC, madsbk commented on ucp/_libs/ucx_rkey.pyx
>      ucp_rkey_destroy(rkey_handle)
Wait, the last patch failed

2021-04-26 08:43 UTC, pentschev commented on ucp/_libs/ucx_rkey.pyx
>      ucp_rkey_destroy(rkey_handle)
Remove leftover ucp_rkey_destroy call

2021-04-26 08:58 UTC, merged

2021-04-26 08:58 UTC, pentschev commented
Thanks @madsbk , this is in.