Ensure no pre-allocation occurs when --reuse-alloc not specified
rapidsai/ucx-py pull request #880
Opened 2022-09-22 10:01 UTC by pentschev

Fixes the behavior of benchmarks when `--reuse-alloc` is not specified, before this change objects would be pre-allocated, even though that didn't guarantee the underlying memory would be allocated before running the transfer. Only `--reuse-alloc` should pre-allocate objects or buffers.

2022-09-22 11:06 UTC, wence- reviewed
Possible simplification?

2022-09-22 11:06 UTC, wence- commented on ucp/benchmarks/backends/ucp_async.py
> +
Rationale for this is also that we don't really look at the results of all the `msg_send_list` etc...

2022-09-22 13:55 UTC, pentschev commented on ucp/benchmarks/backends/ucp_async.py
> +
I tried to combine the changes you suggested here in https://github.com/rapidsai/ucx-py/pull/880/commits/3e748b8b403cb1cdfc59461694156e1d4aa9e2ef, could you take another look?

2022-09-22 15:00 UTC, wence- requested changes
Sorry, I realise I produced a load of bad advice in the last round of comments (which most of my suggestions are trying to undo now). That aside, this change looks overall good, thanks!

2022-09-22 16:30 UTC, pentschev commented
> Sorry, I realise I produced a load of bad advice in the last round of comments (which most of my suggestions are trying to undo now). That aside, this change looks overall good, thanks!

Your new comments are correct I believe. No worries, I should also have been more attentive while I was doing those changes, I've been distracted and overlooked the `gather` issues, even though we've had those before. These are the times I would love a big red failure, unfortunate data races are much sneakier. 🙂

2022-09-26 14:20 UTC, wence- approved these changes
Thanks, looks great!

2022-09-26 17:05 UTC, merged