Add wheel builds (#901)
rapidsai/ucx-py pull request #907
Opened 2022-12-19 20:02 UTC by quasiben

This PR adds support for building wheels of ucx-py.

Authors:
  - Vyas Ramasubramani (https://github.com/vyasr)
  - Benjamin Zaitlen (https://github.com/quasiben)
  - Sevag H (https://github.com/sevagh)

Approvers:
  - Lawrence Mitchell (https://github.com/wence-)
  - Joseph (https://github.com/jolorunyomi)

URL: https://github.com/rapidsai/ucx-py/pull/901

cc @sevagh

2022-12-19 20:04 UTC, sevagh approved these changes

2022-12-19 21:31 UTC, vyasr requested changes
I see [historical forward merge PRs](https://github.com/rapidsai/ucx-py/pulls?q=is%3Apr+forward), why wasn't this pulled into 0.30 via such a PR?

2022-12-19 22:06 UTC, jakirkham commented
Asking OPS offline about Vyas' question above

2022-12-20 16:28 UTC, sevagh commented
The forward merger was fixed and the wheels.yml file was merged in, so we don't need this anymore.

2022-12-20 16:28 UTC, closed without merging