Handle ``NVMLError_NotSupported`` exception
rapidsai/ucx-py pull request #983
Opened 2023-08-23 22:22 UTC by rjzamora

Closes https://github.com/rapidsai/ucx-py/issues/982

2023-08-23 22:23 UTC, rjzamora commented on ucp/__init__.py
> +                continue
@pentschev - Is it "correct" to leave the `large_bar1` element as `False` for devices without Bar1 access?

2023-08-24 07:01 UTC, pentschev requested changes

2023-08-24 07:01 UTC, pentschev commented on ucp/__init__.py
> +                continue
```suggestion
                # Bar1 access not supported on this device, set it to
                # zero (always lower than device memory).
                bar1_total = 0
```

2023-08-24 07:46 UTC, pentschev approved these changes
Thanks @rjzamora for working on this PR! 😄

2023-08-24 07:46 UTC, pentschev commented
/merge

2023-08-24 07:46 UTC, merged